export const CREATE_ORDER = "CREATE_ORDER";
export const FETCH_ORDER = "FETCH_ORDER";
export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const CHANGE_ORDER_STEPS = "CHANGE_ORDER_STEPS";
export const RESET_ORDER = "RESET_ORDER";
export const PAY_ORDER = "PAY_ORDER";
export const FECTH_USER_ORDERS = "FECTH_USER_ORDERS";
