export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";


